//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.20 at 10:34:30 AM BST 
//


package rapidFit.data;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TwoDScanType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TwoDScanType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="X_Param" type="{}ScanParamType"/>
 *         &lt;element name="Y_Param" type="{}ScanParamType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TwoDScanType", propOrder = {
    "xParam",
    "yParam"
})
public class TwoDScanType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "X_Param", required = true)
    protected ScanParamType xParam;
    @XmlElement(name = "Y_Param", required = true)
    protected ScanParamType yParam;

    /**
     * Gets the value of the xParam property.
     * 
     * @return
     *     possible object is
     *     {@link ScanParamType }
     *     
     */
    public ScanParamType getXParam() {
        return xParam;
    }

    /**
     * Sets the value of the xParam property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScanParamType }
     *     
     */
    public void setXParam(ScanParamType value) {
        this.xParam = value;
    }

    /**
     * Gets the value of the yParam property.
     * 
     * @return
     *     possible object is
     *     {@link ScanParamType }
     *     
     */
    public ScanParamType getYParam() {
        return yParam;
    }

    /**
     * Sets the value of the yParam property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScanParamType }
     *     
     */
    public void setYParam(ScanParamType value) {
        this.yParam = value;
    }

}
