//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.27 at 05:05:34 PM BST 
//


package rapidFit.rpfit;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ConstraintFunctionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ConstraintFunctionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element name="ExternalConstraint" type="{}ExternalConstraintType"/>
 *         &lt;element name="ExternalConstMatrix" type="{}ExternalConstMatrixType"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ConstraintFunctionType", propOrder = {
    "externalConstraintOrExternalConstMatrix"
})
public class ConstraintFunctionType {

    @XmlElements({
        @XmlElement(name = "ExternalConstraint", type = ExternalConstraintType.class),
        @XmlElement(name = "ExternalConstMatrix", type = ExternalConstMatrixType.class)
    })
    protected List<Object> externalConstraintOrExternalConstMatrix;

    /**
     * Gets the value of the externalConstraintOrExternalConstMatrix property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the externalConstraintOrExternalConstMatrix property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExternalConstraintOrExternalConstMatrix().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ExternalConstraintType }
     * {@link ExternalConstMatrixType }
     * 
     * 
     */
    public List<Object> getExternalConstraintOrExternalConstMatrix() {
        if (externalConstraintOrExternalConstMatrix == null) {
            externalConstraintOrExternalConstMatrix = new ArrayList<Object>();
        }
        return this.externalConstraintOrExternalConstMatrix;
    }

}
