//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.01 at 03:37:19 PM BST 
//


package rapidFit.rpfit;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ContourPlotType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ContourPlotType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="XParameter" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="YParameter" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ContourPlotType", propOrder = {

})
public class ContourPlotType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "XParameter", required = true)
    protected String xParameter;
    @XmlElement(name = "YParameter", required = true)
    protected String yParameter;

    /**
     * Gets the value of the xParameter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXParameter() {
        return xParameter;
    }

    /**
     * Sets the value of the xParameter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXParameter(String value) {
        this.xParameter = value;
    }

    /**
     * Gets the value of the yParameter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getYParameter() {
        return yParameter;
    }

    /**
     * Sets the value of the yParameter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setYParameter(String value) {
        this.yParameter = value;
    }

}
