//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.17 at 03:05:45 PM BST 
//


package rapidFit.rpfit;

import java.io.Serializable;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FitFunctionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FitFunctionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FunctionName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="UseGSLNumericalIntegration" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="FixedIntegrationPoints" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="WeightName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AlphaName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Trace" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Strategy" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Threads" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="SetIntegratorTest" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="NormaliseWeights" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="SingleNormaliseWeights" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="OffSetNLL" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="RequiredParameterOrder" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FitFunctionType", propOrder = {
    "functionName",
    "useGSLNumericalIntegration",
    "fixedIntegrationPoints",
    "weightName",
    "alphaName",
    "trace",
    "strategy",
    "threads",
    "setIntegratorTest",
    "normaliseWeights",
    "singleNormaliseWeights",
    "offSetNLL",
    "requiredParameterOrder"
})
public class FitFunctionType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "FunctionName")
    protected String functionName;
    @XmlElement(name = "UseGSLNumericalIntegration")
    protected Boolean useGSLNumericalIntegration;
    @XmlElement(name = "FixedIntegrationPoints")
    protected BigInteger fixedIntegrationPoints;
    @XmlElement(name = "WeightName")
    protected String weightName;
    @XmlElement(name = "AlphaName")
    protected String alphaName;
    @XmlElement(name = "Trace")
    protected String trace;
    @XmlElement(name = "Strategy")
    protected String strategy;
    @XmlElement(name = "Threads")
    protected BigInteger threads;
    @XmlElement(name = "SetIntegratorTest")
    protected Boolean setIntegratorTest;
    @XmlElement(name = "NormaliseWeights")
    protected Boolean normaliseWeights;
    @XmlElement(name = "SingleNormaliseWeights")
    protected Boolean singleNormaliseWeights;
    @XmlElement(name = "OffSetNLL")
    protected Boolean offSetNLL;
    @XmlElement(name = "RequiredParameterOrder")
    protected String requiredParameterOrder;

    /**
     * Gets the value of the functionName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFunctionName() {
        return functionName;
    }

    /**
     * Sets the value of the functionName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFunctionName(String value) {
        this.functionName = value;
    }

    /**
     * Gets the value of the useGSLNumericalIntegration property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isUseGSLNumericalIntegration() {
        return useGSLNumericalIntegration;
    }

    /**
     * Sets the value of the useGSLNumericalIntegration property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUseGSLNumericalIntegration(Boolean value) {
        this.useGSLNumericalIntegration = value;
    }

    /**
     * Gets the value of the fixedIntegrationPoints property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFixedIntegrationPoints() {
        return fixedIntegrationPoints;
    }

    /**
     * Sets the value of the fixedIntegrationPoints property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFixedIntegrationPoints(BigInteger value) {
        this.fixedIntegrationPoints = value;
    }

    /**
     * Gets the value of the weightName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWeightName() {
        return weightName;
    }

    /**
     * Sets the value of the weightName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWeightName(String value) {
        this.weightName = value;
    }

    /**
     * Gets the value of the alphaName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlphaName() {
        return alphaName;
    }

    /**
     * Sets the value of the alphaName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlphaName(String value) {
        this.alphaName = value;
    }

    /**
     * Gets the value of the trace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrace() {
        return trace;
    }

    /**
     * Sets the value of the trace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrace(String value) {
        this.trace = value;
    }

    /**
     * Gets the value of the strategy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrategy() {
        return strategy;
    }

    /**
     * Sets the value of the strategy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrategy(String value) {
        this.strategy = value;
    }

    /**
     * Gets the value of the threads property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getThreads() {
        return threads;
    }

    /**
     * Sets the value of the threads property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setThreads(BigInteger value) {
        this.threads = value;
    }

    /**
     * Gets the value of the setIntegratorTest property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSetIntegratorTest() {
        return setIntegratorTest;
    }

    /**
     * Sets the value of the setIntegratorTest property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSetIntegratorTest(Boolean value) {
        this.setIntegratorTest = value;
    }

    /**
     * Gets the value of the normaliseWeights property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isNormaliseWeights() {
        return normaliseWeights;
    }

    /**
     * Sets the value of the normaliseWeights property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setNormaliseWeights(Boolean value) {
        this.normaliseWeights = value;
    }

    /**
     * Gets the value of the singleNormaliseWeights property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSingleNormaliseWeights() {
        return singleNormaliseWeights;
    }

    /**
     * Sets the value of the singleNormaliseWeights property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSingleNormaliseWeights(Boolean value) {
        this.singleNormaliseWeights = value;
    }

    /**
     * Gets the value of the offSetNLL property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isOffSetNLL() {
        return offSetNLL;
    }

    /**
     * Sets the value of the offSetNLL property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setOffSetNLL(Boolean value) {
        this.offSetNLL = value;
    }

    /**
     * Gets the value of the requiredParameterOrder property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequiredParameterOrder() {
        return requiredParameterOrder;
    }

    /**
     * Sets the value of the requiredParameterOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequiredParameterOrder(String value) {
        this.requiredParameterOrder = value;
    }

}
