//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.02 at 03:15:59 PM BST 
//


package rapidFit.rpfit;

import java.io.Serializable;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for MinimiserType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MinimiserType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MinimiserName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="NSigma" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="MaxSteps" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="GradTolerance" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="ConfigureMinimiser" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Quality" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="MultiMini" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MinimiserType", propOrder = {
    "minimiserName",
    "nSigma",
    "maxSteps",
    "gradTolerance",
    "configureMinimiser",
    "quality",
    "multiMini"
})
public class MinimiserType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "MinimiserName")
    protected String minimiserName;
    @XmlElement(name = "NSigma")
    protected BigInteger nSigma;
    @XmlElement(name = "MaxSteps")
    protected BigInteger maxSteps;
    @XmlElement(name = "GradTolerance", type = String.class)
    @XmlJavaTypeAdapter(Adapter1 .class)
    @XmlSchemaType(name = "double")
    protected Double gradTolerance;
    @XmlElement(name = "ConfigureMinimiser")
    protected String configureMinimiser;
    @XmlElement(name = "Quality")
    protected BigInteger quality;
    @XmlElement(name = "MultiMini")
    protected Boolean multiMini;

    /**
     * Gets the value of the minimiserName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMinimiserName() {
        return minimiserName;
    }

    /**
     * Sets the value of the minimiserName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMinimiserName(String value) {
        this.minimiserName = value;
    }

    /**
     * Gets the value of the nSigma property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNSigma() {
        return nSigma;
    }

    /**
     * Sets the value of the nSigma property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNSigma(BigInteger value) {
        this.nSigma = value;
    }

    /**
     * Gets the value of the maxSteps property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMaxSteps() {
        return maxSteps;
    }

    /**
     * Sets the value of the maxSteps property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMaxSteps(BigInteger value) {
        this.maxSteps = value;
    }

    /**
     * Gets the value of the gradTolerance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Double getGradTolerance() {
        return gradTolerance;
    }

    /**
     * Sets the value of the gradTolerance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGradTolerance(Double value) {
        this.gradTolerance = value;
    }

    /**
     * Gets the value of the configureMinimiser property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConfigureMinimiser() {
        return configureMinimiser;
    }

    /**
     * Sets the value of the configureMinimiser property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConfigureMinimiser(String value) {
        this.configureMinimiser = value;
    }

    /**
     * Gets the value of the quality property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getQuality() {
        return quality;
    }

    /**
     * Sets the value of the quality property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setQuality(BigInteger value) {
        this.quality = value;
    }

    /**
     * Gets the value of the multiMini property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isMultiMini() {
        return multiMini;
    }

    /**
     * Sets the value of the multiMini property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setMultiMini(Boolean value) {
        this.multiMini = value;
    }

}
