//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.01 at 10:15:29 AM BST 
//


package rapidFit.rpfit;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OutputType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OutputType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ContourPlot" type="{}ContourPlotType" minOccurs="0"/>
 *         &lt;element name="Projection" type="{}PlotType" minOccurs="0"/>
 *         &lt;element name="ComponentProjection" type="{}PlotType" minOccurs="0"/>
 *         &lt;element name="DoPullPlots" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="Scan" type="{}ParamType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OutputType", propOrder = {
    "contourPlot",
    "projection",
    "componentProjection",
    "doPullPlots",
    "scan"
})
public class OutputType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "ContourPlot")
    protected ContourPlotType contourPlot;
    @XmlElement(name = "Projection")
    protected PlotType projection;
    @XmlElement(name = "ComponentProjection")
    protected PlotType componentProjection;
    @XmlElement(name = "DoPullPlots")
    protected Object doPullPlots;
    @XmlElement(name = "Scan")
    protected List<ParamType> scan;

    /**
     * Gets the value of the contourPlot property.
     * 
     * @return
     *     possible object is
     *     {@link ContourPlotType }
     *     
     */
    public ContourPlotType getContourPlot() {
        return contourPlot;
    }

    /**
     * Sets the value of the contourPlot property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContourPlotType }
     *     
     */
    public void setContourPlot(ContourPlotType value) {
        this.contourPlot = value;
    }

    /**
     * Gets the value of the projection property.
     * 
     * @return
     *     possible object is
     *     {@link PlotType }
     *     
     */
    public PlotType getProjection() {
        return projection;
    }

    /**
     * Sets the value of the projection property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlotType }
     *     
     */
    public void setProjection(PlotType value) {
        this.projection = value;
    }

    /**
     * Gets the value of the componentProjection property.
     * 
     * @return
     *     possible object is
     *     {@link PlotType }
     *     
     */
    public PlotType getComponentProjection() {
        return componentProjection;
    }

    /**
     * Sets the value of the componentProjection property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlotType }
     *     
     */
    public void setComponentProjection(PlotType value) {
        this.componentProjection = value;
    }

    /**
     * Gets the value of the doPullPlots property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getDoPullPlots() {
        return doPullPlots;
    }

    /**
     * Sets the value of the doPullPlots property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setDoPullPlots(Object value) {
        this.doPullPlots = value;
    }

    /**
     * Gets the value of the scan property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the scan property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getScan().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ParamType }
     * 
     * 
     */
    public List<ParamType> getScan() {
        if (scan == null) {
            scan = new ArrayList<ParamType>();
        }
        return this.scan;
    }

}
