//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.15 at 10:22:38 AM BST 
//


package rapidFit.rpfit;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OutputType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OutputType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ComponentProjection" type="{}ComponentProjectionType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="DoPullPlots" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="Scan" type="{}ScanParamType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="TwoDScan" type="{}TwoDScanType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OutputType", propOrder = {
    "componentProjection",
    "doPullPlots",
    "scan",
    "twoDScan"
})
public class OutputType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "ComponentProjection")
    protected List<ComponentProjectionType> componentProjection;
    @XmlElement(name = "DoPullPlots")
    protected Object doPullPlots;
    @XmlElement(name = "Scan")
    protected List<ScanParamType> scan;
    @XmlElement(name = "TwoDScan")
    protected List<TwoDScanType> twoDScan;

    /**
     * Gets the value of the componentProjection property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the componentProjection property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getComponentProjection().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ComponentProjectionType }
     * 
     * 
     */
    public List<ComponentProjectionType> getComponentProjection() {
        if (componentProjection == null) {
            componentProjection = new ArrayList<ComponentProjectionType>();
        }
        return this.componentProjection;
    }

    /**
     * Gets the value of the doPullPlots property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getDoPullPlots() {
        return doPullPlots;
    }

    /**
     * Sets the value of the doPullPlots property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setDoPullPlots(Object value) {
        this.doPullPlots = value;
    }

    /**
     * Gets the value of the scan property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the scan property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getScan().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ScanParamType }
     * 
     * 
     */
    public List<ScanParamType> getScan() {
        if (scan == null) {
            scan = new ArrayList<ScanParamType>();
        }
        return this.scan;
    }

    /**
     * Gets the value of the twoDScan property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the twoDScan property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTwoDScan().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TwoDScanType }
     * 
     * 
     */
    public List<TwoDScanType> getTwoDScan() {
        if (twoDScan == null) {
            twoDScan = new ArrayList<TwoDScanType>();
        }
        return this.twoDScan;
    }

}
