//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.08 at 09:45:05 AM BST 
//


package rapidFit.rpfit;

import java.io.Serializable;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RapidFitType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RapidFitType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ParameterSet" type="{}ParameterSetType"/>
 *         &lt;element name="Minimiser" type="{}MinimiserType"/>
 *         &lt;element name="FitFunction" type="{}FitFunctionType"/>
 *         &lt;element name="NumberRepeats" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="CommonPhaseSpace" type="{}CommonPhaseSpaceType" minOccurs="0"/>
 *         &lt;element name="CommonPDF" type="{}PDFExpressionType" minOccurs="0"/>
 *         &lt;element name="Precalculator" type="{}PrecalculatorType" minOccurs="0"/>
 *         &lt;element name="Seed" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="ToFit" type="{}ToFitType" maxOccurs="unbounded"/>
 *         &lt;element name="Output" type="{}OutputType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RapidFitType", propOrder = {
    "parameterSet",
    "minimiser",
    "fitFunction",
    "numberRepeats",
    "commonPhaseSpace",
    "commonPDF",
    "precalculator",
    "seed",
    "toFit",
    "output"
})
public class RapidFitType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "ParameterSet", required = true)
    protected ParameterSetType parameterSet;
    @XmlElement(name = "Minimiser", required = true)
    protected MinimiserType minimiser;
    @XmlElement(name = "FitFunction", required = true)
    protected FitFunctionType fitFunction;
    @XmlElement(name = "NumberRepeats", required = true)
    protected BigInteger numberRepeats;
    @XmlElement(name = "CommonPhaseSpace")
    protected CommonPhaseSpaceType commonPhaseSpace;
    @XmlElement(name = "CommonPDF")
    protected PDFExpressionType commonPDF;
    @XmlElement(name = "Precalculator")
    protected PrecalculatorType precalculator;
    @XmlElement(name = "Seed")
    protected BigInteger seed;
    @XmlElement(name = "ToFit", required = true)
    protected List<ToFitType> toFit;
    @XmlElement(name = "Output", required = true)
    protected OutputType output;

    /**
     * Gets the value of the parameterSet property.
     * 
     * @return
     *     possible object is
     *     {@link ParameterSetType }
     *     
     */
    public ParameterSetType getParameterSet() {
        return parameterSet;
    }

    /**
     * Sets the value of the parameterSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParameterSetType }
     *     
     */
    public void setParameterSet(ParameterSetType value) {
        this.parameterSet = value;
    }

    /**
     * Gets the value of the minimiser property.
     * 
     * @return
     *     possible object is
     *     {@link MinimiserType }
     *     
     */
    public MinimiserType getMinimiser() {
        return minimiser;
    }

    /**
     * Sets the value of the minimiser property.
     * 
     * @param value
     *     allowed object is
     *     {@link MinimiserType }
     *     
     */
    public void setMinimiser(MinimiserType value) {
        this.minimiser = value;
    }

    /**
     * Gets the value of the fitFunction property.
     * 
     * @return
     *     possible object is
     *     {@link FitFunctionType }
     *     
     */
    public FitFunctionType getFitFunction() {
        return fitFunction;
    }

    /**
     * Sets the value of the fitFunction property.
     * 
     * @param value
     *     allowed object is
     *     {@link FitFunctionType }
     *     
     */
    public void setFitFunction(FitFunctionType value) {
        this.fitFunction = value;
    }

    /**
     * Gets the value of the numberRepeats property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumberRepeats() {
        return numberRepeats;
    }

    /**
     * Sets the value of the numberRepeats property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumberRepeats(BigInteger value) {
        this.numberRepeats = value;
    }

    /**
     * Gets the value of the commonPhaseSpace property.
     * 
     * @return
     *     possible object is
     *     {@link CommonPhaseSpaceType }
     *     
     */
    public CommonPhaseSpaceType getCommonPhaseSpace() {
        return commonPhaseSpace;
    }

    /**
     * Sets the value of the commonPhaseSpace property.
     * 
     * @param value
     *     allowed object is
     *     {@link CommonPhaseSpaceType }
     *     
     */
    public void setCommonPhaseSpace(CommonPhaseSpaceType value) {
        this.commonPhaseSpace = value;
    }

    /**
     * Gets the value of the commonPDF property.
     * 
     * @return
     *     possible object is
     *     {@link PDFExpressionType }
     *     
     */
    public PDFExpressionType getCommonPDF() {
        return commonPDF;
    }

    /**
     * Sets the value of the commonPDF property.
     * 
     * @param value
     *     allowed object is
     *     {@link PDFExpressionType }
     *     
     */
    public void setCommonPDF(PDFExpressionType value) {
        this.commonPDF = value;
    }

    /**
     * Gets the value of the precalculator property.
     * 
     * @return
     *     possible object is
     *     {@link PrecalculatorType }
     *     
     */
    public PrecalculatorType getPrecalculator() {
        return precalculator;
    }

    /**
     * Sets the value of the precalculator property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrecalculatorType }
     *     
     */
    public void setPrecalculator(PrecalculatorType value) {
        this.precalculator = value;
    }

    /**
     * Gets the value of the seed property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSeed() {
        return seed;
    }

    /**
     * Sets the value of the seed property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSeed(BigInteger value) {
        this.seed = value;
    }

    /**
     * Gets the value of the toFit property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the toFit property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getToFit().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ToFitType }
     * 
     * 
     */
    public List<ToFitType> getToFit() {
        if (toFit == null) {
            toFit = new ArrayList<ToFitType>();
        }
        return this.toFit;
    }

    /**
     * Gets the value of the output property.
     * 
     * @return
     *     possible object is
     *     {@link OutputType }
     *     
     */
    public OutputType getOutput() {
        return output;
    }

    /**
     * Sets the value of the output property.
     * 
     * @param value
     *     allowed object is
     *     {@link OutputType }
     *     
     */
    public void setOutput(OutputType value) {
        this.output = value;
    }

}
